import Image from "next/image";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "about",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="">
      <main className="">
        <h1>About page</h1>
      </main>
    </div>
  );
}
