import Image from "next/image";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "about",
  description: "Generated by create next app",
};

export default function AboutPage() {
  return (
    <div className="container mx-auto px-4">
      <main className="py-10">
        <h1 className="text-4xl font-bold text-gray-800">About page</h1>
        <p className="mt-4 text-gray-600">
          Esta página ya tendrá el Header automáticamente gracias al layout.
        </p>
      </main>
    </div>
  );
}
